/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.demo;

//import org.postgresql.Driver;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class App1 {
    public static void main(String[] args) throws SQLException, ClassNotFoundException {
        //  Driver driver=new Driver();
        //     DriverManager.registerDriver(driver);
        //step1 register driver
        Class.forName("org.postgresql.Driver");

        //step2 open connection
        String url = "jdbc:postgresql://localhost:5432/training";
        String user="postgres",password="scooby";

        Connection connection = DriverManager.getConnection(url,user,password);
        //create statement
        Statement statement = connection.createStatement();

        String insertQueryText="insert into students(id, username,age) values(4,'nikhil',23)";
        int rowsUpdated=statement.executeUpdate(insertQueryText);
        System.out.println("rows updated="+rowsUpdated);

        String fetchQueryText = "select * from students";
        ResultSet resultSet = statement.executeQuery(fetchQueryText);
        List<Student> students=new ArrayList<>();

        while (resultSet.next()) {
            long id = resultSet.getLong("id");
            String username = resultSet.getString("username");
            int age = resultSet.getInt("age");
            System.out.println("id=" + id + " username=" + username + " age=" + age);
            Student student=new Student();
            student.setId(id);
            student.setUsername(username);
            student.setAge(age);
            students.add(student);
        }


        connection.close();
    }
}
